// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AgroGuia.Dominio.Modelo.Entidades;

public partial class AgroGuiaIA_DBContext : DbContext
{
    public AgroGuiaIA_DBContext(DbContextOptions<AgroGuiaIA_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Conversaciones> Conversaciones { get; set; }

    public virtual DbSet<EmbeddingChunks> EmbeddingChunks { get; set; }

    public virtual DbSet<Mensajes> Mensajes { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Conversaciones>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Conversa__3214EC07202609C4");

            entity.HasIndex(e => e.UsuarioId, "IX_Conversaciones_UsuarioId");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaActualizacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Titulo)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.Usuario).WithMany(p => p.Conversaciones)
                .HasForeignKey(d => d.UsuarioId)
                .HasConstraintName("FK__Conversac__Usuar__412EB0B6");
        });

        modelBuilder.Entity<EmbeddingChunks>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Embeddin__3214EC07FEDCD2C7");

            entity.HasIndex(e => e.Cultivo, "IX_EmbeddingChunks_Cultivo");

            entity.HasIndex(e => new { e.Cultivo, e.Tema }, "IX_EmbeddingChunks_Cultivo_Tema");

            entity.HasIndex(e => e.Fuente, "IX_EmbeddingChunks_Fuente");

            entity.HasIndex(e => e.Tema, "IX_EmbeddingChunks_Tema");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Contenido).IsRequired();
            entity.Property(e => e.Cultivo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FechaCarga).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Fuente)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.PalabrasClave)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.Tema)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Titulo)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Mensajes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Mensajes__3214EC0745E3E171");

            entity.HasIndex(e => e.ConversacionId, "IX_Mensajes_ConversacionId");

            entity.Property(e => e.Contenido).IsRequired();
            entity.Property(e => e.Fecha).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Conversacion).WithMany(p => p.Mensajes)
                .HasForeignKey(d => d.ConversacionId)
                .HasConstraintName("FK__Mensajes__Conver__44FF419A");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC07F526A3E3");

            entity.HasIndex(e => e.Email, "IX_Usuarios_Email");

            entity.HasIndex(e => e.Email, "UQ__Usuarios__A9D1053428199598").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FechaRegistro).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.RefreshToken)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Agricultor");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}