// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgroGuia.Dominio.Modelo.Entidades;

public partial class Conversaciones
{
    public long Id { get; set; }

    public long UsuarioId { get; set; }

    public string Titulo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Mensajes> Mensajes { get; set; } = new List<Mensajes>();

    public virtual Usuarios Usuario { get; set; }
}