// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgroGuia.Dominio.Modelo.Entidades;

public partial class EmbeddingChunks
{
    public long Id { get; set; }

    public string Titulo { get; set; }

    public string Contenido { get; set; }


    public string Fuente { get; set; }

    public string Cultivo { get; set; }

    public string Tema { get; set; }

    public string PalabrasClave { get; set; }

    public DateTime? FechaCarga { get; set; }

    public bool? Activo { get; set; }

    public string VectorEmbedding { get; set; }
    public string Metadata { get; set; }
}