// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgroGuia.Dominio.Modelo.Entidades;

public partial class Mensajes
{
    public long Id { get; set; }

    public long ConversacionId { get; set; }

    public string Rol { get; set; }

    public string Contenido { get; set; }

    public DateTime? Fecha { get; set; }

    public int? Tokens { get; set; }

    public virtual Conversaciones Conversacion { get; set; }
}