// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgroGuia.Dominio.Modelo.Entidades;

public partial class Usuarios
{
    public long Id { get; set; }

    public string NombreCompleto { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Telefono { get; set; }

    public string Rol { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public DateTime? UltimoAcceso { get; set; }

    public bool Activo { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiry { get; set; }

    public virtual ICollection<Conversaciones> Conversaciones { get; set; } = new List<Conversaciones>();
}